#========================================================================
#应用上下文配置
server:
  servlet:
    context-path: /hh-bp-authorization
  tomcat: 
     accept-count: 150
     min-spare-threads: 80
     max-threads: 250  
#spring组件相关配置
spring:
  application:
    name: hh-bp-authorization
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      use-global-data-source-stat: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,slf4j
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        login-username: admin
        login-password: authbiostime
        reset-enable: false
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-parameter-set-log-enabled: false
          statement-execute-after-log-enabled: false
          # 打印可执行sql
          statement-executable-sql-log-enable: true
          statement-parameter-clear-log-enable: false
          statement-close-after-log-enabled: false
          # 打印预处理sql语句，false为不打印
          statement-prepare-after-log-enabled: false
          statement-prepare-call-after-log-enabled: false
  messages:
    basename: i18n/messages

#========================================================================
#logback组件相关配置
logging:
  config: classpath:logback-spring.xml


#========================================================================
#MyBatis组件相关配置
mybatis:
#  指定pojo在mapper.xml中的包别名，省得写全路径
  type-aliases-package: com.biostime.bp.authorization.domain
  mapper-locations: classpath:repository/**/*.xml

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

repwdEmail:
  host: smtp.office365.com
  port: 587
  username: itadmin2@hh.global
  pwd: Biostime123
  expire: 86400
  title: Reset login password
  url: '#/login?changePwd=true&token={0}&verifySeq={1}'
  content: Dear {0} :<br/><br/>You reset the login password of "H&H Global Anti-counterfeiting System " through the mailbox, please reset the password through the link below. If the link cannot be adjusted in this email, please copy the link below and open it in the browser:<br/><br/><a href="{1}">{2}</a><br/>The link expires hours after the mail arrives {3}.<br/><br/>H&H Global Anti-counterfeiting System